// Généré par extension/build_defaults.py à partir de rules.toml, themes.toml et config.toml.
// Ne pas modifier à la main : relancer `python extension/build_defaults.py`.
(function (root) {
  const WMT = (root.WMT = root.WMT || {});
  const DEFAULTS = {
    "version": 5,
    "rules": [
      {
        "name": "Cinéma/Séries/Acteurs",
        "color": "#fbbf24",
        "keywords": [
          "acteur",
          "actrice",
          "comedien",
          "comedienne",
          "cineaste",
          "realisateur",
          "realisatrice",
          "scenariste(?! de (bande dessinee|bd|jeux?))",
          "films?",
          "telefilm",
          "court[ -]metrage",
          "long[ -]metrage",
          "cinema\\w*",
          "serie televisee",
          "serie de television",
          "serie d'animation",
          "mini-?series?",
          "saison de serie",
          "sitcom",
          "telenovela",
          "feuilleton televise",
          "documentaire",
          "franchise mediatique",
          "metteur en scene",
          "metteuse en scene",
          "product(eur|rice) de (cinema|films?)",
          "societe de production",
          "direct(eur|rice) de la photographie",
          "doubleur",
          "doubleuse"
        ],
        "titleKeywords": []
      },
      {
        "name": "Royauté",
        "color": "#a78bfa",
        "keywords": [
          "rois?",
          "reines?",
          "prince",
          "princesse",
          "monarque",
          "dauphine? de france",
          "empereur",
          "imperatrice",
          "dynastie",
          "souverain",
          "souveraine",
          "tsar",
          "tsarine",
          "sultan",
          "sultane",
          "pharaon",
          "infante?",
          "emir",
          "shah",
          "maharaja\\w*",
          "archiduc",
          "archiduchesse",
          "grand-duc",
          "grande-duchesse",
          "famille (royale|imperiale)",
          "maison (royale|imperiale)",
          "(reine|roi|prince) consort"
        ],
        "titleKeywords": [
          "^liste des (rois|reines|souverains|monarques|empereurs|imperatrices|pharaons|sultans|tsars|princes|emirs)\\b"
        ]
      },
      {
        "name": "Musique",
        "color": "#5eead4",
        "keywords": [
          "chanteur",
          "chanteuse",
          "musicien",
          "musicienne",
          "musique",
          "musicale?s?",
          "musicaux",
          "projet musical",
          "groupe (musical|vocal)",
          "boys? band",
          "girls? band",
          "girl group",
          "groupe de (musique|rock|pop|rap|hip-hop|metal|jazz|variete|punk|reggae|funk|soul|blues|folk|electro|techno|country|ska)\\w*",
          "hip-hop",
          "rap",
          "rock",
          "jazz",
          "reggae",
          "heavy metal",
          "death metal",
          "black metal",
          "album",
          "chanson",
          "single",
          "symphonie",
          "sonate",
          "concerto",
          "opera",
          "compositeur",
          "compositrice",
          "auteur-compositeur\\w*",
          "autrice-compositrice\\w*",
          "rappeur",
          "rappeuse",
          "dj",
          "disc[ -]jockey",
          "pianiste",
          "guitariste",
          "bassiste",
          "batteur",
          "batteuse",
          "percussionniste",
          "violoniste",
          "violoncelliste",
          "contrebassiste",
          "saxophoniste",
          "trompettiste",
          "flutiste",
          "clarinettiste",
          "organiste",
          "claveciniste",
          "harpiste",
          "accordeoniste",
          "balafoniste",
          "sitar\\w*",
          "luthier",
          "orchestre",
          "chef d'orchestre",
          "soprano",
          "mezzo-soprano",
          "tenor",
          "baryton",
          "contralto",
          "cantatrice",
          "instrument de musique",
          "instrument a (cordes|vent|percussion|clavier)",
          "technique vocale",
          "registre (vocal|de voix)",
          "maison de disques",
          "label discographique"
        ],
        "titleKeywords": [
          "\\((groupe|ep)\\)",
          "^(sonate|symphonie|concerto|requiem|cantate|quatuor a cordes)\\b"
        ]
      },
      {
        "name": "Mythologie",
        "color": "#fb7185",
        "keywords": [
          "mytholog\\w*",
          "mythique",
          "divinite\\w*",
          "dieux",
          "deesses?",
          "demi-dieu",
          "dieu (de|du|des|d'|grec|romain|egyptien|nordique|celte|hindou|azteque|maya|inca)\\w*",
          "titan",
          "titanide",
          "nymphe\\w*",
          "heros (grec|de la mythologie|legendaire|mythologique)",
          "filles? de zeus",
          "fils de zeus",
          "personnage legendaire",
          "creature (legendaire|mythologique|fantastique|imaginaire|mythique)",
          "(figure|creature|animal|monstre) (heraldique )?imaginaire",
          "monstre (legendaire|mythologique)",
          "cyclope",
          "centaure",
          "minotaure",
          "gorgone",
          "antiquite",
          "antique",
          "grece antique",
          "rome antique",
          "egypte antique",
          "ancienne egypte",
          "(?<!saint-)empire romain(?! germanique)",
          "republique romaine",
          "consul romain",
          "empereur romain",
          "cite (grecque|antique)",
          "hellenisti\\w*",
          "grec ancien",
          "athenes",
          "athenien\\w*",
          "sparte",
          "spartiate",
          "acropole",
          "temple (grec|romain)",
          "(roi|reine|pharaon) d'egypte",
          "(?<!catholique )(?<!saint-empire )romaine?s?(?! germanique)",
          "grecque? antique",
          "pharaon",
          "pyramide",
          "hieroglyphe\\w*",
          "mesopotami\\w*",
          "babylon\\w*",
          "sumer\\w*",
          "assyri\\w*",
          "hittite\\w*",
          "perse antique",
          "achemenide\\w*",
          "carthag\\w*",
          "etrusque\\w*",
          "gaulois\\w*",
          "thrace\\w*",
          "macedoine antique",
          "legion romaine",
          "legionnaire romain",
          "gladiateur\\w*",
          "(philosophe|poete|poetesse|dramaturge|historien|orateur|general|homme politique|sculpteur|mathematicien) (grec|romain|athenien|carthaginois)",
          "amphitheatre",
          "theatre antique",
          "oracle",
          "troie",
          "iliade",
          "odyssee",
          "heros de la mythologie",
          "age du (bronze|fer)",
          "paleochretien\\w*"
        ],
        "titleKeywords": [
          "ptolemee",
          "cleopatre",
          "ramses",
          "alexandre le grand",
          "jules cesar",
          "neron",
          "caligula",
          "hadrien",
          "trajan",
          "^auguste$",
          "nefertiti",
          "toutankhamon",
          "pericles",
          "hannibal",
          "vercingetorix"
        ]
      },
      {
        "name": "Maths",
        "color": "#01c7fc",
        "keywords": [
          "mathemati\\w*",
          "entiers? (naturels?|relatifs?|positifs?|strictement positifs?)",
          "nombre entier",
          "nombres? (premiers?|reels?|complexes?|rationnels?|irrationnels?|transcendants?|parfaits?|algebriques?|pairs?|impairs?|entiers?)",
          "theoreme",
          "lemme",
          "conjecture",
          "axiome\\w*",
          "corollaire",
          "geometri\\w*",
          "algebr\\w*",
          "equations?",
          "inequation\\w*",
          "polynom\\w*",
          "integrale\\w*",
          "derivee",
          "topologi\\w*",
          "probabilit\\w*",
          "test statistique",
          "statistique (mathematique|inferentielle|descriptive)",
          "theorie des (graphes|nombres|ensembles|categories|groupes|jeux)",
          "graphes?",
          "polyedre\\w*",
          "polygone\\w*",
          "fractal\\w*",
          "arithmeti\\w*",
          "trigonometri\\w*",
          "booleen\\w*",
          "booleenne\\w*",
          "logique (mathematique|formelle)",
          "demonstration (mathematique|formelle)"
        ],
        "titleKeywords": [
          "^(theoreme|lemme|conjecture|axiome|corollaire|equation|inegalite)\\b",
          "\\((nombre|analyse|logique|analyse complexe)\\)",
          "booleen\\w*",
          "valeurs? (propres?|singulieres?)"
        ]
      },
      {
        "name": "Automobile",
        "color": "#86efac",
        "keywords": [
          "automobiles?",
          "voitures?",
          "vehicules? (automobiles?|utilitaires?|de tourisme|electriques?|hybrides?|de sport)",
          "supercar",
          "hypercar",
          "concept car",
          "roadster",
          "berline",
          "cabriolet",
          "constructeur automobile",
          "marque automobile",
          "modele d'automobile",
          "pilote (automobile|de course|de rallye|de formule \\w+|d'endurance|de nascar)",
          "formule (1|un|2|3|e)",
          "grand prix (automobile|de formule \\w+)",
          "rallye\\w*",
          "courses? (automobiles?|de cotes?)",
          "endurance automobile",
          "24 heures du mans",
          "nascar",
          "indycar",
          "karting",
          "sport automobile",
          "circuit automobile",
          "jeu video de course",
          "simulation automobile"
        ],
        "titleKeywords": [
          "^f1 \\d{4}",
          "^formule 1",
          "^grand prix (automobile|de formule)",
          "^(gran turismo|need for speed|forza (motorsport|horizon))\\b",
          "^(peugeot|renault|citroen|ferrari|porsche|lamborghini|bugatti|aston martin|bmw|audi|volkswagen|fiat|alfa romeo|lancia|maserati|bentley|rolls-royce|chevrolet|dodge|chrysler|cadillac|de dion-bouton|panhard|simca|delahaye|hispano-suiza|mclaren|skoda|volvo|mazda|subaru|nissan|toyota|dacia|lada|mercedes-benz|jaguar|ford|opel|tesla) [a-z0-9]"
        ]
      },
      {
        "name": "Roumanie",
        "color": "#f87171",
        "keywords": [
          "roumain\\w*",
          "roumanie",
          "bucarest",
          "transylvan\\w*",
          "valachie",
          "valaque\\w*",
          "moldav\\w*",
          "dacie",
          "dobroudja",
          "carpates",
          "banat",
          "bucovine",
          "cluj\\w*",
          "timisoara",
          "iasi",
          "brasov",
          "sibiu",
          "constanta",
          "craiova",
          "oradea",
          "palinka",
          "tuica",
          "mamaliga",
          "sarmale"
        ],
        "titleKeywords": [
          "roumanie",
          "bucarest",
          "palinka",
          "tuica",
          "^dacia\\b"
        ]
      },
      {
        "name": "Ski",
        "color": "#22d3ee",
        "keywords": [
          "skis?",
          "skieur",
          "skieuse",
          "skieurs",
          "skieuses",
          "ski (alpin|de fond|acrobatique|nordique|de randonnee|freestyle)",
          "saut a ski",
          "sauteur a ski",
          "sauteuse a ski",
          "station de (ski|sports d'hiver)",
          "domaine skiable",
          "slalom\\w*",
          "super-g",
          "biathl\\w*",
          "combine nordique",
          "snowboard\\w*",
          "fondeur",
          "fondeuse",
          "telemark"
        ],
        "titleKeywords": [
          "^ski ",
          "coupe du monde de ski",
          "championnats? du monde de ski"
        ]
      },
      {
        "name": "Finance",
        "color": "#e879f9",
        "keywords": [
          "financ\\w*",
          "bours\\w*",
          "banque",
          "banques",
          "bancaire\\w*",
          "banquier\\w*",
          "investissement\\w*",
          "investisseur\\w*",
          "action (de|d'une) (societe|entreprise)",
          "actionna\\w*",
          "obligations?",
          "dividende\\w*",
          "indice boursier",
          "marche (financier|boursier|des changes|monetaire)",
          "marches financiers",
          "fonds (d'investissement|speculatif|de pension|souverain|commun de placement)",
          "hedge fund",
          "capital-risque",
          "private equity",
          "gestion d'actifs",
          "gestionnaire (d'actifs|de fonds)",
          "(compagnie|societe|groupe) d'assurances?",
          "assureur\\w*",
          "etablissement de credit",
          "taux d'(interet|change)",
          "inflation",
          "deflation",
          "monnaie\\w*",
          "devise\\w*",
          "cryptomonnaie\\w*",
          "bitcoin",
          "blockchain",
          "krach",
          "speculat\\w*",
          "trader\\w*",
          "courtier\\w*",
          "courtage",
          "produit derive",
          "produits derives",
          "titrisation",
          "introduction en bourse",
          "capitalisation boursiere",
          "economiste\\w*",
          "dette (publique|souveraine)",
          "faillite bancaire",
          "wall street"
        ],
        "titleKeywords": [
          "\\((finance|economie|bourse)\\)",
          "^(banque|bourse|indice) "
        ]
      },
      {
        "name": "Physique",
        "color": "#facc15",
        "keywords": [
          "physique",
          "physicien\\w*",
          "astrophysi\\w*",
          "mecanique (quantique|classique|des fluides|statistique)",
          "quantique\\w*",
          "relativite",
          "thermodynami\\w*",
          "electromagneti\\w*",
          "optique",
          "particules? (elementaires?|subatomiques?)",
          "boson\\w*",
          "fermion\\w*",
          "quark\\w*",
          "lepton\\w*",
          "neutrino\\w*",
          "photon\\w*",
          "electrons?",
          "proton\\w*",
          "neutron\\w*",
          "atome\\w*",
          "atomique\\w*",
          "nucleaire\\w*",
          "radioactiv\\w*",
          "fission",
          "fusion nucleaire",
          "accelerateur de particules",
          "gravitation\\w*",
          "gravitationnel\\w*",
          "cosmolog\\w*",
          "trou noir",
          "matiere noire",
          "energie noire",
          "big bang",
          "onde\\w* (electromagnetique|gravitationnelle|sonore)\\w*",
          "unite (de mesure|de base|derivee)",
          "grandeur physique",
          "constante physique",
          "laser\\w*",
          "supraconduct\\w*",
          "semi-conducteur\\w*",
          "rayonnement (electromagnetique|ionisant|cosmique|thermique)",
          "spectroscop\\w*"
        ],
        "titleKeywords": [
          "\\((physique|unite|mecanique|optique|electromagnetisme)\\)",
          "^constante de ",
          "^effet (doppler|joule|photoelectrique|compton|tunnel|hall|zeeman|stark|casimir|kerr|faraday|peltier|seebeck|thomson|cherenkov|tcherenkov|meissner|mpemba|magnus|venturi|coanda)"
        ]
      },
      {
        "name": "Substances",
        "color": "#4ade80",
        "keywords": [
          "molecule\\w*",
          "compose (chimique|organique|inorganique)",
          "composes chimiques",
          "type d'entite chimique",
          "classe (structurale )?de composes chimiques",
          "entite chimique",
          "substance\\w*",
          "medicament\\w*",
          "principe actif",
          "molecule active",
          "pharmac\\w*",
          "drogue\\w*",
          "stupefiant\\w*",
          "psychotrope\\w*",
          "psychoactive?s?",
          "hallucinogene\\w*",
          "opiace\\w*",
          "opioide\\w*",
          "cannabinoide\\w*",
          "cannabis",
          "cocaine",
          "amphetamine\\w*",
          "alcaloide\\w*",
          "antibiotique\\w*",
          "antidepresseur\\w*",
          "anxiolytique\\w*",
          "analgesique\\w*",
          "anesthesique\\w*",
          "hormone\\w*",
          "vitamine\\w*",
          "neurotransmetteur\\w*",
          "toxine\\w*",
          "poison\\w*",
          "acide \\w+",
          "oxyde\\w*",
          "hydrocarbure\\w*",
          "alcool\\w*",
          "enzyme\\w*",
          "proteine\\w*",
          "polymere\\w*",
          "solvant\\w*",
          "explosif\\w*",
          "pesticide\\w*"
        ],
        "titleKeywords": [
          "\\((molecule|medicament|drogue|chimie|compose chimique)\\)",
          "^acide "
        ]
      },
      {
        "name": "Plateau de Saclay",
        "color": "#38bdf8",
        "keywords": [
          "saclay",
          "universite paris-sud",
          "universite d'orsay",
          "campus d'orsay",
          "faculte des sciences d'orsay"
        ],
        "titleKeywords": [
          "saclay",
          "^(orsay|palaiseau|gif-sur-yvette|bures-sur-yvette|les ulis|vauhallan|villiers-le-bacle|villebon-sur-yvette|verrieres-le-buisson|jouy-en-josas|les loges-en-josas|toussus-le-noble|magny-les-hameaux)( \\((essonne|yvelines)\\))?$",
          "^(saint-aubin|igny|massy|bievres) \\(essonne\\)$",
          "^(buc|chateaufort) \\(yvelines\\)$",
          "^(yvette|bievre) \\(riviere\\)$",
          "^merantaise$",
          "universite paris-(sud|xi)",
          "universite d'evry(-val-d'essonne)?",
          "universite (de )?versailles[- ]saint-quentin(-en-yvelines)?",
          "^ecole polytechnique( \\(france\\))?$",
          "institut polytechnique de paris",
          "centralesupelec",
          "^ecole centrale paris$",
          "^supelec$",
          "ecole superieure d'electricite",
          "ecole normale superieure de cachan",
          "^hec paris$",
          "ecole des hautes etudes commerciales de paris",
          "agroparistech",
          "^ensta( paris| paristech)?$",
          "ecole nationale superieure de techniques avancees",
          "^ensae( paris| paristech)?$",
          "ecole nationale de la statistique et de l'administration economique",
          "^telecom (paris|paristech|sudparis)$",
          "^ecole nationale superieure des telecommunications$",
          "institut d'optique",
          "^supoptique$",
          "ecole nationale superieure d'informatique pour l'industrie et l'entreprise",
          "^ensiie$",
          "^iut d'orsay$",
          "commissariat a l'energie atomique",
          "synchrotron soleil",
          "^soleil \\(synchrotron\\)$",
          "laboratoire de l'accelerateur lineaire",
          "^ijclab$",
          "laboratoire de physique des (2|deux) infinis",
          "institut de physique nucleaire d'orsay",
          "laboratoire de physique des solides",
          "^onera$",
          "office national d'etudes et de recherches aerospatiales",
          "institut des hautes etudes scientifiques",
          "^ihes$",
          "laboratoire leprince-ringuet",
          "laboratoire d'optique appliquee",
          "laboratoire pour l'utilisation des lasers intenses",
          "institut d'astrophysique spatiale",
          "^neurospin$",
          "orme des merisiers",
          "^saturne \\((accelerateur|synchrotron)\\)$",
          "anneau de collisions d'orsay",
          "institut de chimie des substances naturelles",
          "institut de biologie integrative de la cellule",
          "laboratoire des sciences du climat et de l'environnement",
          "fondation mathematique jacques-hadamard",
          "laboratoire de mathematiques d'orsay",
          "centre de mathematiques laurent-schwartz",
          "centre de nanosciences et de nanotechnologies",
          "institut photovoltaique d'ile-de-france",
          "^ligne 18 du metro de paris$",
          "^aerodrome de toussus-le-noble$",
          "^gare (de |d')(orsay-ville|le guichet|lozere|palaiseau|palaiseau-villebon|bures-sur-yvette|gif-sur-yvette|courcelle-sur-yvette|massy-palaiseau)$",
          "^(irene joliot-curie|frederic joliot-curie|albert fert|pierre-gilles de gennes|gerard mourou|anne l'huillier|pierre agostini|anatole abragam|jules horowitz|louis leprince-ringuet)$",
          "^(alexander grothendieck|rene thom|pierre deligne|alain connes|maxim kontsevitch|laurent lafforgue|hugo duminil-copin|mikhail gromov|dennis sullivan|thibault damour|jean-pierre bourguignon)$",
          "^(jean-christophe yoccoz|wendelin werner|ngo bao chau|laurent schwartz)$"
        ],
        "cross": true
      },
      {
        "name": "Shiny",
        "color": "#f0abfc",
        "keywords": [],
        "titleKeywords": [],
        "shiny": true
      }
    ],
    "themes": [
      {
        "name": "Sport",
        "color": "#a3e635",
        "keywords": [
          "footballeur",
          "footballeuse",
          "cycliste",
          "perchiste",
          "grimpeur",
          "grimpeuse",
          "athlete",
          "joueur de \\w+",
          "joueuse de \\w+",
          "tennisman",
          "tenniswoman",
          "boxeur",
          "boxeuse",
          "nageur",
          "nageuse",
          "rugbyman",
          "basketteur",
          "basketteuse",
          "handballeur",
          "handballeuse",
          "pilote (automobile|de course|de moto)",
          "skieur",
          "skieuse",
          "judoka",
          "entraineur",
          "entraineuse",
          "sportif",
          "sportive",
          "club de \\w+",
          "equipe de \\w+",
          "championnat",
          "coupe du monde",
          "jeux olympiques",
          "stade"
        ],
        "titleKeywords": [
          "^equipe de",
          "championnat",
          "coupe du monde",
          "jeux olympiques"
        ]
      },
      {
        "name": "Politique",
        "color": "#f87171",
        "keywords": [
          "homme politique",
          "femme politique",
          "personnalite politique",
          "parti politique",
          "depute",
          "deputee",
          "senateur",
          "senatrice",
          "ministre",
          "president",
          "presidente",
          "premier ministre",
          "maire",
          "diplomate",
          "politico\\w*",
          "election",
          "syndicat\\w*"
        ],
        "titleKeywords": []
      },
      {
        "name": "Littérature",
        "color": "#22d3ee",
        "keywords": [
          "ecrivain",
          "ecrivaine",
          "romancier",
          "romanciere",
          "poete",
          "poetesse",
          "dramaturge",
          "essayiste",
          "livre",
          "roman",
          "recueil",
          "nouvelle",
          "bande dessinee",
          "manga",
          "auteur",
          "autrice"
        ],
        "titleKeywords": []
      },
      {
        "name": "Géographie/Lieux",
        "color": "#e879f9",
        "keywords": [
          "commune",
          "ville",
          "village",
          "capitale",
          "pays",
          "region",
          "departement",
          "province",
          "ile",
          "archipel",
          "fleuve",
          "riviere",
          "lac",
          "montagne",
          "massif",
          "volcan",
          "desert",
          "quartier",
          "arrondissement",
          "canton",
          "etat (federe|des etats-unis)"
        ],
        "titleKeywords": []
      },
      {
        "name": "Histoire/Militaire",
        "color": "#facc15",
        "keywords": [
          "bataille",
          "guerre",
          "siege",
          "traite",
          "revolution",
          "armee",
          "militaire",
          "general",
          "marechal",
          "helicoptere",
          "avion de (chasse|combat)",
          "char d'assaut",
          "navire",
          "cuirasse",
          "porte-avions",
          "espion",
          "espionne",
          "resistant",
          "resistante"
        ],
        "titleKeywords": []
      },
      {
        "name": "Sciences",
        "color": "#4ade80",
        "keywords": [
          "physicien\\w*",
          "chimiste",
          "biologiste",
          "astronome",
          "astrophysicien\\w*",
          "ingenieur\\w*",
          "scientifique",
          "chercheur",
          "chercheuse",
          "medecin",
          "element chimique",
          "molecule",
          "planete",
          "etoile",
          "galaxie",
          "theorie",
          "aerospatial\\w*",
          "physique",
          "chimie",
          "biologie"
        ],
        "titleKeywords": []
      },
      {
        "name": "Philosophie",
        "color": "#38bdf8",
        "keywords": [
          "philosophe",
          "philosophi\\w*",
          "courant (philosophique|de pensee)",
          "doctrine",
          "ideologie"
        ],
        "titleKeywords": []
      },
      {
        "name": "Nature/Animaux",
        "color": "#c084fc",
        "keywords": [
          "espece",
          "genre (de|d') \\w+",
          "famille de \\w+",
          "oiseau",
          "insecte",
          "mammifere",
          "poisson",
          "reptile",
          "plante",
          "arbre",
          "champignon",
          "animal\\w*",
          "race de \\w+"
        ],
        "titleKeywords": []
      },
      {
        "name": "Tech/Informatique",
        "color": "#2dd4bf",
        "keywords": [
          "logiciel",
          "application",
          "systeme d'exploitation",
          "langage de programmation",
          "site web",
          "reseau social",
          "jeu video",
          "console de jeux?",
          "informatique",
          "smartphone",
          "moteur de recherche"
        ],
        "titleKeywords": [
          "playstation",
          "nintendo",
          "xbox",
          "microsoft",
          "google",
          "apple"
        ]
      },
      {
        "name": "Entreprises/Marques",
        "color": "#fda4af",
        "keywords": [
          "entreprise",
          "societe",
          "marque",
          "constructeur",
          "multinationale",
          "groupe industriel",
          "chaine de \\w+"
        ],
        "titleKeywords": []
      },
      {
        "name": "Religion",
        "color": "#93c5fd",
        "keywords": [
          "pape",
          "saint",
          "sainte",
          "eglise",
          "religion",
          "religieux",
          "religieuse",
          "eveque",
          "cathedrale",
          "abbaye",
          "monastere",
          "theolog\\w*"
        ],
        "titleKeywords": []
      },
      {
        "name": "Arts",
        "color": "#fbbf24",
        "keywords": [
          "peintre",
          "sculpteur",
          "sculptrice",
          "tableau",
          "peinture",
          "sculpture",
          "photographe",
          "architecte",
          "musee",
          "dessinateur",
          "dessinatrice",
          "illustrat\\w*"
        ],
        "titleKeywords": []
      },
      {
        "name": "Médias/TV",
        "color": "#a78bfa",
        "keywords": [
          "animateur",
          "animatrice",
          "journaliste",
          "emission de television",
          "chaine de television",
          "presentateur",
          "presentatrice",
          "youtubeur",
          "youtubeuse",
          "streameur",
          "humoriste"
        ],
        "titleKeywords": []
      },
      {
        "name": "Listes Wikipédia",
        "color": "#f472b6",
        "keywords": [
          "page de liste de wikimedia",
          "liste"
        ],
        "titleKeywords": [
          "^liste d",
          "^deces en"
        ]
      }
    ],
    "settings": {
      "minCount": 10,
      "wikidata": true,
      "contact": "",
      "pageDelay": 1000,
      "highlight": true,
      "highlightStyle": "ring",
      "autoPrompt": true,
      "accountType": "free",
      "notifyFull": true,
      "notifyEach": false,
      "autoReveal": true,
      "revealDelay": 200,
      "naturalRhythm": true,
      "autoChain": true,
      "sellRarities": [],
      "sellKeep": true
    }
  };
  WMT.defaults = { config: () => JSON.parse(JSON.stringify(DEFAULTS)) };
})(globalThis);
